import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

fs.mkdirSync('artifacts', { recursive: true });

const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'artifacts/home-desktop.png', fullPage: true });
await page.getByRole('button', { name: 'Options for Oakwood Valley' }).click();
await page.getByRole('button', { name: 'Rename world', exact: true }).click();
await page.getByLabel('World name', { exact: true }).fill('Oakwood Retreat');
await page.getByRole('button', { name: 'Save name' }).click();
assert.equal(await page.getByRole('button', { name: 'Oakwood Retreat', exact: true }).count(), 1);
await page.getByRole('button', { name: 'Settings', exact: true }).click();
await page.getByRole('button', { name: 'Performance Lower power usage' }).click();
await page.getByRole('switch', { name: 'Show FPS counter' }).click();
assert.equal(JSON.parse(await page.evaluate(() => localStorage.getItem('sandvoxel-settings'))).quality, 'Performance');
await page.getByRole('button', { name: 'Play', exact: true }).click();
await page.getByRole('button', { name: 'Create new world', exact: true }).click();
await page.getByLabel('World name', { exact: true }).fill('Test Meadow');
await page.getByLabel('World seed', { exact: false }).fill('31415');
await page.getByRole('button', { name: 'Create and start exploring' }).click();
await page.getByRole('button', { name: 'Let us explore', exact: true }).waitFor({ timeout: 30000 });
await page.screenshot({ path: 'artifacts/game-welcome.png' });
await page.getByRole('button', { name: 'Let us explore', exact: true }).click();
await page.waitForTimeout(1500);
await page.keyboard.press('Digit4');
await page.keyboard.down('KeyW');
await page.waitForTimeout(700);
await page.keyboard.up('KeyW');
await page.keyboard.press('KeyF');
await page.keyboard.down('Space');
await page.waitForTimeout(700);
await page.keyboard.up('Space');
await page.screenshot({ path: 'artifacts/game-desktop.png' });
await page.keyboard.press('Escape');
await page.waitForTimeout(500);
await page.getByRole('button', { name: 'Save and return home' }).click();
assert.ok(await page.evaluate(() => Object.keys(localStorage).some(key => key.startsWith('sandvoxel-world-'))));
await page.getByRole('button', { name: 'My worlds' }).click();
await page.getByPlaceholder('Find a world').fill('Test Meadow');
assert.equal(await page.locator('.world-card').count(), 1);
await page.screenshot({ path: 'artifacts/library-desktop.png' });
console.log('Desktop checks passed. Browser errors:', errors);

const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
mobile.on('pageerror', error => errors.push(error.message));
await mobile.goto('http://localhost:5173', { waitUntil: 'networkidle' });
assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await mobile.getByRole('button', { name: 'Open navigation' }).tap();
await mobile.getByRole('button', { name: 'My worlds' }).tap();
await mobile.getByRole('button', { name: 'Play Oakwood Retreat', exact: true }).tap();
await mobile.getByRole('button', { name: 'Let us explore', exact: true }).waitFor({ timeout: 30000 });
await mobile.getByRole('button', { name: 'Let us explore', exact: true }).tap();
await mobile.waitForTimeout(1000);
assert.equal(await mobile.locator('.touch-controls').count(), 1);
await mobile.getByRole('button', { name: 'Build', exact: true }).tap();
await mobile.getByRole('button', { name: 'Mine', exact: true }).tap();
await mobile.getByRole('button', { name: 'Pause game', exact: true }).tap();
await mobile.getByRole('button', { name: 'Save and return home' }).tap();
await mobile.getByRole('button', { name: 'Open navigation' }).tap();
await mobile.getByRole('button', { name: 'Play', exact: true }).tap();
await mobile.screenshot({ path: 'artifacts/home-mobile.png', fullPage: true });
console.log('Mobile checks passed. Browser errors:', errors);
await browser.close();
assert.equal(errors.length, 0);
